	SELECT
        CAST(StartDateET AS DATE) AS DateET,
        SUM(CASE WHEN "0" != 0 THEN 1 ELSE 0 END) AS "0",
        SUM(CASE WHEN "1" != 0 THEN 1 ELSE 0 END) AS "1",
        SUM(CASE WHEN "2" != 0 THEN 1 ELSE 0 END) AS "2",
        SUM(CASE WHEN "3" != 0 THEN 1 ELSE 0 END) AS "3",
        SUM(CASE WHEN "4" != 0 THEN 1 ELSE 0 END) AS "4",
        SUM(CASE WHEN "5" != 0 THEN 1 ELSE 0 END) AS "5",
        SUM(CASE WHEN "6" != 0 THEN 1 ELSE 0 END) AS "6",
        SUM(CASE WHEN "7" != 0 THEN 1 ELSE 0 END) AS "7",
        SUM(CASE WHEN "8" != 0 THEN 1 ELSE 0 END) AS "8",
        SUM(CASE WHEN "9" != 0 THEN 1 ELSE 0 END) AS "9",
        SUM(CASE WHEN "10" != 0 THEN 1 ELSE 0 END) AS "10",
        SUM(CASE WHEN "11" != 0 THEN 1 ELSE 0 END) AS "11",
        SUM(CASE WHEN "12" != 0 THEN 1 ELSE 0 END) AS "12",
        SUM(CASE WHEN "13" != 0 THEN 1 ELSE 0 END) AS "13",
        SUM(CASE WHEN "14" != 0 THEN 1 ELSE 0 END) AS "14",
        SUM(CASE WHEN "15" != 0 THEN 1 ELSE 0 END) AS "15",
        SUM(CASE WHEN "16" != 0 THEN 1 ELSE 0 END) AS "16",
        SUM(CASE WHEN "17" != 0 THEN 1 ELSE 0 END) AS "17",
        SUM(CASE WHEN "18" != 0 THEN 1 ELSE 0 END) AS "18",
        SUM(CASE WHEN "19" != 0 THEN 1 ELSE 0 END) AS "19",
        SUM(CASE WHEN "20" != 0 THEN 1 ELSE 0 END) AS "20",
        SUM(CASE WHEN "21" != 0 THEN 1 ELSE 0 END) AS "21",
        SUM(CASE WHEN "22" != 0 THEN 1 ELSE 0 END) AS "22",
        SUM(CASE WHEN "23" != 0 THEN 1 ELSE 0 END) AS "23"
    FROM [dbo].[275Bottlenecks_Wide]
    GROUP BY CAST(StartDateET AS DATE)
    ORDER BY CAST(StartDateET AS DATE)